# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 855)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/vpDiscovery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAppTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblAppTitle.setGeometry(QtCore.QRect(160, 0, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblAppTitle.setFont(font)
        self.lblAppTitle.setAutoFillBackground(True)
        self.lblAppTitle.setTextFormat(QtCore.Qt.PlainText)
        self.lblAppTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAppTitle.setWordWrap(True)
        self.lblAppTitle.setObjectName("lblAppTitle")
        self.pbExit = QtWidgets.QPushButton(self.centralwidget)
        self.pbExit.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pbExit.setObjectName("pbExit")
        self.pbStartCapture = QtWidgets.QPushButton(self.centralwidget)
        self.pbStartCapture.setGeometry(QtCore.QRect(430, 610, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbStartCapture.setFont(font)
        self.pbStartCapture.setStyleSheet("background-color: rgb(0, 230, 111);")
        self.pbStartCapture.setObjectName("pbStartCapture")
        self.cbx_TimeMilliSecs = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_TimeMilliSecs.setGeometry(QtCore.QRect(420, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cbx_TimeMilliSecs.setFont(font)
        self.cbx_TimeMilliSecs.setObjectName("cbx_TimeMilliSecs")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 170, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.pbEndCapture = QtWidgets.QPushButton(self.centralwidget)
        self.pbEndCapture.setGeometry(QtCore.QRect(430, 690, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbEndCapture.setFont(font)
        self.pbEndCapture.setObjectName("pbEndCapture")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 260, 100, 4))
        self.label_5.setStyleSheet("border-color: rgb(116, 116, 116);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setLineWidth(2)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(425, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.pbSavePtCloud = QtWidgets.QPushButton(self.centralwidget)
        self.pbSavePtCloud.setGeometry(QtCore.QRect(420, 760, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbSavePtCloud.setFont(font)
        self.pbSavePtCloud.setStyleSheet("background-color: rgb(0, 230, 111);")
        self.pbSavePtCloud.setObjectName("pbSavePtCloud")
        self.grp_hz2dPlot = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_hz2dPlot.setGeometry(QtCore.QRect(20, 480, 380, 350))
        self.grp_hz2dPlot.setTitle("")
        self.grp_hz2dPlot.setObjectName("grp_hz2dPlot")
        self.grp_vt2dPlot = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_vt2dPlot.setGeometry(QtCore.QRect(560, 480, 380, 350))
        self.grp_vt2dPlot.setTitle("")
        self.grp_vt2dPlot.setObjectName("grp_vt2dPlot")
        self.txtVTcount = QtWidgets.QLineEdit(self.centralwidget)
        self.txtVTcount.setGeometry(QtCore.QRect(420, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txtVTcount.setFont(font)
        self.txtVTcount.setText("")
        self.txtVTcount.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVTcount.setObjectName("txtVTcount")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 470, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(640, 470, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 100, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lblCurDir = QtWidgets.QLabel(self.centralwidget)
        self.lblCurDir.setGeometry(QtCore.QRect(425, 310, 91, 81))
        self.lblCurDir.setStyleSheet("background-color: rgb(0, 200, 200);")
        self.lblCurDir.setText("")
        self.lblCurDir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurDir.setObjectName("lblCurDir")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(425, 270, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.grp_drone_loc2dPlot = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_drone_loc2dPlot.setGeometry(QtCore.QRect(560, 110, 380, 350))
        self.grp_drone_loc2dPlot.setTitle("")
        self.grp_drone_loc2dPlot.setObjectName("grp_drone_loc2dPlot")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(650, 100, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 400, 100, 4))
        self.label_6.setStyleSheet("border-color: rgb(116, 116, 116);")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setLineWidth(2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.lblMsg = QtWidgets.QLabel(self.centralwidget)
        self.lblMsg.setGeometry(QtCore.QRect(26, 830, 911, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMsg.setFont(font)
        self.lblMsg.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lblMsg.setText("")
        self.lblMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMsg.setObjectName("lblMsg")
        self.lstDistances = QtWidgets.QListWidget(self.centralwidget)
        self.lstDistances.setGeometry(QtCore.QRect(410, 490, 141, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lstDistances.setFont(font)
        self.lstDistances.setObjectName("lstDistances")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(420, 460, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.lbl_HZactive = QtWidgets.QLabel(self.centralwidget)
        self.lbl_HZactive.setGeometry(QtCore.QRect(795, 38, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_HZactive.setFont(font)
        self.lbl_HZactive.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_HZactive.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_HZactive.setObjectName("lbl_HZactive")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(420, 410, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lbl_FwdDist = QtWidgets.QLabel(self.centralwidget)
        self.lbl_FwdDist.setGeometry(QtCore.QRect(420, 440, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_FwdDist.setFont(font)
        self.lbl_FwdDist.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_FwdDist.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_FwdDist.setObjectName("lbl_FwdDist")
        self.lbl_VTactive = QtWidgets.QLabel(self.centralwidget)
        self.lbl_VTactive.setGeometry(QtCore.QRect(795, 70, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_VTactive.setFont(font)
        self.lbl_VTactive.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_VTactive.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_VTactive.setObjectName("lbl_VTactive")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(610, 0, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(640, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(640, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.lbl_ZEDstatus = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ZEDstatus.setGeometry(QtCore.QRect(795, 10, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ZEDstatus.setFont(font)
        self.lbl_ZEDstatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_ZEDstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ZEDstatus.setObjectName("lbl_ZEDstatus")
        self.lbl_ZEDimage = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ZEDimage.setGeometry(QtCore.QRect(20, 130, 371, 221))
        self.lbl_ZEDimage.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_ZEDimage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_ZEDimage.setText("")
        self.lbl_ZEDimage.setObjectName("lbl_ZEDimage")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "i3d Camera Logger 1.1"))
        self.lblAppTitle.setText(_translate("MainWindow", "Dual Lidar Data Collection"))
        self.pbExit.setText(_translate("MainWindow", "Exit"))
        self.pbStartCapture.setText(_translate("MainWindow", "Start\n"
"Capture"))
        self.label_3.setText(_translate("MainWindow", "Time Interval Milliseconds"))
        self.pbEndCapture.setText(_translate("MainWindow", "End\n"
"Capture"))
        self.label_7.setText(_translate("MainWindow", "Total Captures"))
        self.pbSavePtCloud.setText(_translate("MainWindow", "Save to\n"
"Pointcloud"))
        self.label_8.setText(_translate("MainWindow", "Horiz. Lidar 2D View"))
        self.label_9.setText(_translate("MainWindow", "Vertical Lidar 2D View"))
        self.label_10.setText(_translate("MainWindow", "Zed Camera View"))
        self.label_11.setText(_translate("MainWindow", "Camera Direction"))
        self.label_12.setText(_translate("MainWindow", "Drone Location"))
        self.label_13.setText(_translate("MainWindow", "Distances"))
        self.lbl_HZactive.setText(_translate("MainWindow", "Active"))
        self.label_14.setText(_translate("MainWindow", "Fwd Proximity"))
        self.lbl_FwdDist.setText(_translate("MainWindow", "100cm"))
        self.lbl_VTactive.setText(_translate("MainWindow", "Active"))
        self.label_15.setText(_translate("MainWindow", "ZED Camera Status:"))
        self.label_16.setText(_translate("MainWindow", "VT Lidar Status:"))
        self.label_17.setText(_translate("MainWindow", "HZ Lidar Status:"))
        self.lbl_ZEDstatus.setText(_translate("MainWindow", "Active"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
