insert into catered_items values (39, 'Aussie Bites', 'Dessert', 32, 1, 'pcs', 7.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (40, 'Chocolate Almonds', 'Dessert', 48, 1, 'oz', 9.59, 'Costco', 'nuts', null, null, 'n', null);
insert into catered_items values (3, 'Chocolate Raisins', 'Dessert', 54, 1, 'oz', 9.29, 'Costco', null, null, null, 'n', null);
insert into catered_items values (4, 'Cinnamon-Walnut Brkfst Bites', 'Breakfast', 22, 1, 'pcs', 6.39, 'Costco', null, null, null, 'n', null);
insert into catered_items values (5, 'Cookies', 'Dessert', 24, 2, 'pcs', 6.49, 'Costco', null, null, null, 'n', null);
insert into catered_items values (6, 'Deli Meat Tray', 'Lunch', 32, 1, 'oz', 17.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (7, 'Dragonfly Cakes Bridal Petits Fours', 'Dessert', 48, 2, 'pcs', 54.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (8, 'Dragonfly Cakes Petits Fours', 'Dessert', 48, 2, 'pcs', 54.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (9, 'Dried Cherries', 'Appetizer', 20, 1, 'oz', 6.79, 'Costco', null, null, null, 'n', null);
insert into catered_items values (10, 'Egg Salad', 'Lunch', 16, 2, 'oz', 6.95, 'Costco' , null, null, null, 'n', null);
insert into catered_items values (11, 'Fresh Fruit Bowl - Big Daddy', 'Lunch', 100, 8, 'oz', 37.5, 'Big Daddy', null, null, null, 'n', null);
insert into catered_items values (12, 'Gourmet Olive Tray', 'Appetizer', 64, 2, 'pcs', 13.79, 'Costco', null, null, null, 'n', null);
insert into catered_items values (13, 'Green Seedless Grapes', 'Lunch', 64, 4, 'oz', 5.79, 'Costco', null, null, null, 'n', null);
insert into catered_items values (14, 'Kosher Puff Cheese Patries', 'Lunch', 48, 3, 'pcs', 9.99, 'Costco', null, 15, 'Frozen:Bake', 'y', 'Frozen:Bake 15min');
insert into catered_items values (15, 'Lemon Bites', 'Dessert', 24, 1, 'pcs', 5.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (16, 'Ling Ling Veggie Spring Rolls', 'Lunch', 45, 2, 'pcs', 9.29, 'Costco', null, 12, 'Frozen:Bake', 'y', 'Frozen:Bake 12min');
insert into catered_items values (17, 'Lox Tray', 'Lunch', 12, 1, 'pcs', 75, 'Big Daddy', null, null, null, 'n', null);
insert into catered_items values (18, 'Mini Blueberry Muffins', 'Dessert', 32, 1, 'pcs', 4.99, 'Costco', 'Fruit & Nuts', null, null, 'n', 'Fruit & Nuts');
insert into catered_items values (19, 'Mini Cinnamon Rolls', 'Dessert', 32, 1, 'pcs', 6.99, 'Costco', 'nuts', null, null, 'n', null);
insert into catered_items values (20, 'Natural Scones', 'Dessert', 28, 1, 'pcs', 6.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (21, 'Olive Feta Taponade', 'Appetizer', 30, 1, 'oz', 8.69, 'Costco', null, null, null, 'n', null);
insert into catered_items values (22, 'Party Cheese Tray', 'Lunch', 32, 1, 'oz', 9.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (23, 'Peanutbutter Triangle Cookies', 'Dessert', 32, 1, 'oz', 1.97, 'Costco', 'peanuts', null, null, 'n', null);
insert into catered_items values (24, 'Pita Chips', 'Appetizer', 28, 1, 'oz', 5.59, 'Costco', null, null, null, 'n', null);
insert into catered_items values (25, 'Pitted Dates', 'Appetizer', 56, 1, 'oz', 6.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (26, 'Pub Mix', 'Appetizer', 44, 1, 'oz', 6.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (27, 'Red Seedless Grapes', 'Lunch', 64, 4, 'oz', 5.79, 'Costco', null, null, null, 'n', null);
insert into catered_items values (28, 'Roasted Red Pepper Hummus', 'Appetizer', 24, 1, 'oz', 4.49, 'Costco', null, null, null, 'n', null);
insert into catered_items values (29, 'Salad Kit', 'Lunch', 16, 4, 'oz', 3.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (30, 'Smoked Whitefish Salad', 'Lunch', 32, 2, 'oz', 8.99, 'Costco', null, null, null, 'n', null);
insert into catered_items values (31, 'Spanakopita', 'Appetizer', 48, 2, 'pcs', 12.89, 'Costco', null, 20, 'Frozen:Bake', 'y', 'Frozen:Bake 20min');
insert into catered_items values (32, 'Spinach-Artichoke-Parmesan Dip', 'Appetizer', 30, 1, 'oz', 7.49, 'Costco', null, null, null, 'n', null);
insert into catered_items values (33, 'Strawberries', 'Lunch', 32, 0.1, 'oz', 4.34, 'Costco', null, null, null, 'n', null);
insert into catered_items values (34, 'Sugar Snap Peas', 'Appetizer', 32, 3, 'oz', 5.79, 'Costco', null, null, null, 'n', null);
insert into catered_items values (35, 'Surimi Tray', 'Lunch', 15, 2, 'pcs', 5.69, 'Costco', null, null, null, 'n', null);
insert into catered_items values (36, 'Sushi Party Tray', 'Lunch', 40, 2, 'pcs', 13.59, 'Costco', null, null, null, 'n', null);
insert into catered_items values (37, 'Tostitos Blk Bean Garlic Chips', 'Appetizer', 26, 1, 'oz', 6.59, 'Costco', null, null, null, 'n', null);
insert into catered_items values (38, 'Veggie Tray', 'Lunch', 64, 4, 'oz', 9.99, 'Costco', null, null, null, 'n', null);
